# Cutsite Analysis Parameters (from cutsites.yaml)
outdir: 'cutsites'
publish_mode: 'copy' # 
bams: 'nfcore-output/bwa/merged_library/*.bam' ## path to bams
znorm_script: 'atacut/src/zNorm.r'
chrom_sizes: 'genome/mm39_sizes.tsv'
macs2:
  shift: -37
  extsize: 75
  keep_dup: 'all'
  model: false
genomecov:
  cut_site:
    upstream: 37
    downstream: 37
  chromosomes_regex: "([1-9]|1[0-9]|X|Y)" 
bigwig_avg:
  bin_size: 10
znorm_params: 
  r_version: '4.4.0'